CREATE TABLE departments (
    id INT NOT NULL AUTO_INCREMENT,
    alias VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY fk_alias (alias),
    PRIMARY KEY(id)
);