ALTER TABLE
    clocks
ADD
    COLUMN course INT,
ADD
    COLUMN degree INT,
ADD
    FOREIGN KEY (course) REFERENCES courses(id) ON DELETE NO ACTION,
ADD
    FOREIGN KEY (degree) REFERENCES degrees(id) ON DELETE NO ACTION;