ALTER TABLE
    clocks
ADD
COLUMN course_id INT,
ADD
COLUMN degree_id INT,
ADD
COLUMN clock_time TIMESTAMP,
ADD
FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE NO ACTION,
ADD
FOREIGN KEY (degree_id) REFERENCES degrees(id) ON DELETE NO ACTION;